import type { Product, ProductCategory } from "@/types/product";

const IMAGE_BASE_URL = "https://adminapi.applegadgetsbd.com/storage/media/large";

export const productCategories = [
  "Laptops",
  "Accessories",
  "Mobile",
  "Tab",
  "Gadget",
  "Home Appliance",
] as const satisfies ProductCategory[];

function image(fileName: string): string {
  return `${IMAGE_BASE_URL}/${fileName}`;
}

export const products: Product[] = [
  {
    id: 1,
    name: "MacBook Air M5 13-Inch",
    category: "Laptops",
    price: 161999,
    stock: 8,
    image: image("MacBook-Air-M4-13-Incha-4820.png"),
  },
  {
    id: 2,
    name: "MacBook Pro M3 14-Inch 8 Core CPU 10 Core GPU",
    category: "Laptops",
    price: 162999,
    stock: 4,
    image: image("MacBook-Pro-M3-14inch-Space-Gray-8357_jpg-7260.png"),
  },
  {
    id: 3,
    name: "MacBook Air M5 15-Inch",
    category: "Laptops",
    price: 185499,
    stock: 6,
    image: image("Macbook-Air-M4-Starlite-7388.jpg"),
  },
  {
    id: 4,
    name: "MacBook Pro M5 14-Inch 16/1TB",
    category: "Laptops",
    price: 246999,
    stock: 3,
    image: image("MacBook-Pro-M3-16inch---Silver-3587.jpg"),
  },
  {
    id: 5,
    name: "MacBook Pro M5 Pro 14-Inch 24/1TB",
    category: "Laptops",
    price: 318999,
    stock: 2,
    image: image("MacBook-Pro-M5-Pro-14-Inch-241TB-18-Core-CPU-20-Core-GPUa-1124.png"),
  },
  {
    id: 6,
    name: "Apple Mac mini M4 10 Core CPU 10 Core GPU - 16/512GB",
    category: "Laptops",
    price: 118999,
    stock: 7,
    image: image("Mac-mini-m2-pro-9143.jpg"),
  },
  {
    id: 7,
    name: "ZOTAC GAMING GeForce RTX 5070 AMP White Edition",
    category: "Accessories",
    price: 138900,
    stock: 5,
    image: image("ZOTAC-GAMING-GeForce-RTX-5070-AMP-White-Edition-12GB-GDDR7-Graphics-Card-2205.jpg"),
  },
  {
    id: 8,
    name: "CORSAIR Vengeance LPX DDR4 3200MHz Desktop RAM",
    category: "Accessories",
    price: 8000,
    stock: 10,
    image: image("Web-Mokup-Recovered-3157.png"),
  },
  {
    id: 9,
    name: "MSI B840M GAMING WIFI6E AM5 mATX Motherboard",
    category: "Accessories",
    price: 19400,
    stock: 6,
    image: image("MSI-B840M-GAMING-WIFI6E-AM5-mATX-Motherboard-5517.png"),
  },
  {
    id: 10,
    name: "Royal Kludge RK R65 RGB Hotswappable Mechanical Keyboard",
    category: "Accessories",
    price: 3999,
    stock: 14,
    image: image("Royal-Kludge-RK-R65-RGB-Hotswappable-Mechanical-Keyboard-4276.jpg"),
  },
  {
    id: 11,
    name: "T-Wolf T70 Tri Mode RGB Mechanical Gaming Keyboard",
    category: "Accessories",
    price: 3599,
    stock: 0,
    image: image("T-Wolf-T70-Tri-Mode-RGB-Mechanical-Gaming-Keyboard-7828.jpg"),
  },
  {
    id: 12,
    name: "ESR Geo Digital Pencil for iPad",
    category: "Accessories",
    price: 4000,
    stock: 9,
    image: image("ESR-Geo-Digital-Pencil-for-iPad-Black-7514.jpg"),
  },
  {
    id: 13,
    name: "Apple 40W Dynamic Power Adapter with 60W Max",
    category: "Accessories",
    price: 7000,
    stock: 15,
    image: image("Apple-40W-Dynamic-Power-Adapter-with-60W-Maxs-4557.png"),
  },
  {
    id: 14,
    name: "Anker A1638 Nano 45W Power Bank - 10000mAh",
    category: "Accessories",
    price: 4900,
    stock: 11,
    image: image("Anker-A1638-Nano-45W-Power-Bank-with-Built-In-Retractable-USB-C-Cable-4979.png"),
  },
  {
    id: 15,
    name: "Nothing Phone (4a) Pro",
    category: "Mobile",
    price: 56500,
    stock: 5,
    image: image("Nothing-Phone-(4a)-Proa-2762.png"),
  },
  {
    id: 16,
    name: "Galaxy A57 5G",
    category: "Mobile",
    price: 43999,
    stock: 13,
    image: image("Galaxy-A57-5G-6910.png"),
  },
  {
    id: 17,
    name: "iPhone 17",
    category: "Mobile",
    price: 106499,
    stock: 4,
    image: image("iPhone-17-Sage-8941.jpg"),
  },
  {
    id: 18,
    name: "iPhone 17 Pro Max",
    category: "Mobile",
    price: 155499,
    stock: 2,
    image: image("iPhone-17-Pro-Max-Cosmic-Orange-4556.jpg"),
  },
  {
    id: 19,
    name: "Honor 600 Pro 5G",
    category: "Mobile",
    price: 77999,
    stock: 6,
    image: image("Honor-600-Pro-5G-9101.png"),
  },
  {
    id: 20,
    name: "Pixel 7",
    category: "Mobile",
    price: 36499,
    stock: 12,
    image: image("Pixel-7-Lemongrass-7348.jpg"),
  },
  {
    id: 21,
    name: "Motorola Edge 60 Pro 5G",
    category: "Mobile",
    price: 39499,
    stock: 7,
    image: image("Motorola-Edge-60-Pro-5Ga-4221.png"),
  },
  {
    id: 22,
    name: "Galaxy S25 Ultra 5G",
    category: "Mobile",
    price: 99499,
    stock: 0,
    image: image("Galaxy-S25-Ultra-5G-Titanium-Silver-Blue-1865.jpg"),
  },
  {
    id: 23,
    name: "Redmi Note 15 5G",
    category: "Mobile",
    price: 27500,
    stock: 16,
    image: image("Redmi-Note-15-5G-3331.png"),
  },
  {
    id: 24,
    name: "Honor 600 5G",
    category: "Mobile",
    price: 61000,
    stock: 1,
    image: image("Honor-600-5Ga-3851.png"),
  },
  {
    id: 25,
    name: "Xiaomi Pad 7",
    category: "Tab",
    price: 37499,
    stock: 10,
    image: image("Xiaomi-Pad-7-blue-6536.jpg"),
  },
  {
    id: 26,
    name: "Galaxy TAB A11+",
    category: "Tab",
    price: 26999,
    stock: 9,
    image: image("Galaxy-TAB-A11+rge-2585.png"),
  },
  {
    id: 27,
    name: "iPad Air M4 - 2026",
    category: "Tab",
    price: 87999,
    stock: 3,
    image: image("iPad-Air-M3---2025a-2380.png"),
  },
  {
    id: 28,
    name: "iPad 11th Gen - 2025",
    category: "Tab",
    price: 53999,
    stock: 7,
    image: image("iPad-10.9-10th-Gen---2022-Yellow-6240.jpg"),
  },
  {
    id: 29,
    name: "Galaxy Tab S9",
    category: "Tab",
    price: 60499,
    stock: 0,
    image: image("Galaxy-Tab-S9-Graphite-3477.jpg"),
  },
  {
    id: 30,
    name: "Galaxy Tab S10 FE",
    category: "Tab",
    price: 45499,
    stock: 5,
    image: image("Galaxy-Tab-S10-FEas-3434.png"),
  },
  {
    id: 31,
    name: "iPad Pro M5 2025",
    category: "Tab",
    price: 149499,
    stock: 2,
    image: image("iPad-Pro-M5-2025-black-7891.png"),
  },
  {
    id: 32,
    name: "Redmi Pad 2",
    category: "Tab",
    price: 22299,
    stock: 8,
    image: image("Redmi-Pad-2gdf-9287.png"),
  },
  {
    id: 33,
    name: "Redmi Watch Move AMOLED Bluetooth Calling Smartwatch",
    category: "Gadget",
    price: 2599,
    stock: 18,
    image: image("Redmi-Watch-Move-AMOLED-Bluetooth-Calling-Smartwatchdfgh-9013.png"),
  },
  {
    id: 34,
    name: "CMF by Nothing Watch Pro 2 BT Calling Smart Watch",
    category: "Gadget",
    price: 5599,
    stock: 12,
    image: image("CMF-by-Nothing-Watch-Pro-2-BT-calling-Smart-Watchaaa-9168.png"),
  },
  {
    id: 35,
    name: "Apple Watch SE 3",
    category: "Gadget",
    price: 33999,
    stock: 4,
    image: image("Apple-Watch-SE-3-9687.png"),
  },
  {
    id: 36,
    name: "AirPods Pro (2nd generation) USB-C",
    category: "Gadget",
    price: 22500,
    stock: 6,
    image: image("AirPods-Pro-(2nd-generation)-USB‐C-3421.png"),
  },
  {
    id: 37,
    name: "Apple AirPods 4",
    category: "Gadget",
    price: 13799,
    stock: 11,
    image: image("Apple-AirPods-4-2341.png"),
  },
  {
    id: 38,
    name: "Anker Soundcore R60i NC TWS Earbuds",
    category: "Gadget",
    price: 3099,
    stock: 20,
    image: image("Anker-Soundcore-R60i-NC-TWS-Earbudssaa-9941.png"),
  },
  {
    id: 39,
    name: "QCY MeloBuds N20 Pro Earbuds",
    category: "Gadget",
    price: 2549,
    stock: 14,
    image: image("QCY-MeloBuds-N20-Pro-Earbuds-9271.png"),
  },
  {
    id: 40,
    name: "OnePlus Bullets Wireless Z3",
    category: "Gadget",
    price: 2000,
    stock: 10,
    image: image("OnePlus-Bullets-Wireless-Z3a-9457.png"),
  },
  {
    id: 41,
    name: "Huawei Band 11",
    category: "Gadget",
    price: 5500,
    stock: 9,
    image: image("Huawei-Band-11sd-8016.png"),
  },
  {
    id: 42,
    name: "Philips NA231 Air Fryer - 6.2L",
    category: "Home Appliance",
    price: 12550,
    stock: 6,
    image: image("Philips-NA231-Air-Fryer---6.2L-6524.png"),
  },
  {
    id: 43,
    name: "PHILIPS NA120/00 Air Fryer 4.2L",
    category: "Home Appliance",
    price: 7600,
    stock: 8,
    image: image("PHILIPS-NA12000-Air-Fryer-4.2L-6906.png"),
  },
  {
    id: 44,
    name: "TCL 65C6K 65 Inch Premium QD-Mini LED TV",
    category: "Home Appliance",
    price: 123999,
    stock: 2,
    image: image("TCL-65C6K-65-Inch-Premium-QD-Mini-LED-TV-6013.jpg"),
  },
  {
    id: 45,
    name: "Haier H32S80GFX 32 Inch QLED FHD Android Google TV",
    category: "Home Appliance",
    price: 27999,
    stock: 10,
    image: image("Haier-H32S80GFX-32-Inch-QLED-FHD-Android-Google-TV-1934.png"),
  },
  {
    id: 46,
    name: "Philips HL7757 3 Jars Mixer Grinder - 750W",
    category: "Home Appliance",
    price: 6000,
    stock: 7,
    image: image("Philips-HL7757-3-Jars-Mixer-Grinder---750W-7177.png"),
  },
  {
    id: 47,
    name: "EcoFlow River 2 Max Portable Power Station",
    category: "Home Appliance",
    price: 42499,
    stock: 3,
    image: image("EcoFlow-River-2-Max-Portable-Power-Station-5919.png"),
  },
  {
    id: 48,
    name: "Hitachi RBG410P6PBX-TH-GBK No Frost Refrigerator - 366L",
    category: "Home Appliance",
    price: 107999,
    stock: 1,
    image: image("RBG410P6PBX-TH-GBK-1-6021.png"),
  },
  {
    id: 49,
    name: "Gree GS-18XSMA4V Shimo Split Inverter AC - 1.5 Ton",
    category: "Home Appliance",
    price: 64499,
    stock: 4,
    image: image("Gree-GS-18XSMA4V-Shimo-Split-Inverter-Air-Conditioner---1.5-Ton-9812.png"),
  },
  {
    id: 50,
    name: "Vision 751248 VSN-Flaming Infrared Cooker - 2000W",
    category: "Home Appliance",
    price: 4000,
    stock: 10,
    image: image("Vision-751248-VSN-Flaming-Infrared-Cooker---2000W-7917.png"),
  },
];

export function isProductCategory(value: string | null): value is ProductCategory {
  return productCategories.includes(value as ProductCategory);
}
